version: "3.8"

services:
  cart:
    container_name: cart
    build:
      context: ./cart
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  loms:
    container_name: loms
    build:
      context: ./loms
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
